name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v5.2.0
        with:
          python-version-file: "pyproject.toml"

      - name: Build package
        run: uv build

      - name: Save dist folder
        uses: actions/upload-artifact@v4
        with:
          path: dist/
          name: python-package-build
          if-no-files-found: error

  pypi-publish:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: pypi
      url: https://pypi.org/p/pyrdf-prefix

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v4

      - name: Get build artifact
        uses: actions/download-artifact@v4
        with:
          path: dist/
          name: python-package-build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
